---
title: "Euclidean Expression Distance"
author: "Joyner Cruz"
date: "2025-01-07"
output: html_document
---

```{r}
####Euclidean Expression Distance####
#The purpose of this code is to calculate the euclidean distance of gene expression between two conditions for genes of interest, considering the proportion of expression in each cluster as a dimension. This can give a general idea of the similarity of overall expression pattern in the same tissue in different conditions.

#This code assumes your data is in Seurat format. 
```

```{r}
#Load the required libraries:
library(dplyr)
library(Seurat)
library(ggplot2)
library(stats)
```

```{r}
#Step 1: Choose your genes of interest (GOI)

#Could hand select a few genes:
GOI<-c("gene1","gene2","gene3","...")


#In my case, I looked at all genes that were induced after irradiation, like this:
Markers<-FindMarkers(seurat_object,ident.1="4000_Rads",only.pos=T,min.pct=0.01,logfc.threshold=0)
  
#Applied some filters, like taking p_val_adj<0.05
Markers2<-Markers%>%
  filter(p_val_adj<0.05,avg_log2FC>0.1,pct.1>=0.01&pct.2>=0.01)

Markers2$gene_name<-rownames(Markers2)

GOI<-Markers2$gene_name
```

```{r}
#Step 2: Separate your object into the two conditions, e.g. irradiated vs unirradiated

Idents(seurat_object)<-"condition.ident"
R4K<-subset(seurat_object,ident="4000_Rads")
R0K<-subset(seurat_object,ident="0_Rads")
```


```{r}
#Step 3: Extract the non-log transformed, average expression of your genes for each cluster in each condition. Group.by let's you pick what cluster annotations you want to use for this analysis.

avg_expression_df_R0K<-as.data.frame(t(as.data.frame(AverageExpression(object = R0K,group.by = "region.ident",features=GOI,layer="data"))))

avg_expression_df_R4K<-as.data.frame(t(as.data.frame(AverageExpression(object = R4K,group.by = "region.ident",features=GOI,layer="data"))))
```


```{r}
#Step 4: Generate a table containing Euclidean distance and Herfindahl-Hirschman Index (HHI) scores for each gene of interest

#define a function that turns each value in a vector into its proportion contribution to the sum of the vector
Proportion_Transform<-function(vector){
  return(vector/sum(vector))
}

#Create a dataframe with Euclidean distances for each gene. 
condition_distance_df <- data.frame(gene_name=character(), condition_distance=numeric(),HHI_R0K=numeric(),HHI_R4K=numeric()) 
for (gene in GOI){

#retrieve de-logged average expression in each cluster for given gene
gene_i_R4K<-avg_expression_df_R4K[,gene]
gene_i_R0K<-avg_expression_df_R0K[,gene]

#Transform average expression values into proportions
gene_i_R4K_norm<-Proportion_Transform(gene_i_R4K)
gene_i_R0K_norm<-Proportion_Transform(gene_i_R0K)

#Calculate Euclidean distance between conditions using proportion values
comparison_mat<-rbind(gene_i_R0K_norm,gene_i_R4K_norm)
distance_gene<-dist(comparison_mat, method = "euclidean", diag = FALSE, upper = FALSE)

#Calculate HHI scores for gene
HHI_R0K_i<-sum(gene_i_R0K_norm^2)
HHI_R4K_i<-sum(gene_i_R4K_norm^2)

#Add this information as a row to the table
condition_distance_df<-condition_distance_df%>% 
  add_row(gene_name = gene, condition_distance = distance_gene[1],
          HHI_R0K=HHI_R0K_i,HHI_R4K=HHI_R4K_i)
}

#If desired, can add in log2FC info. In this case, I will use inner_join() to join the original Marker table generated above:
condition_distance_df<-condition_distance_df%>%
  inner_join(Markers2,by="gene_name")
#This table has a lot of information- it's worth saving it, e.g. with write.csv(). Condition_distance is the Euclidean distance. The higher this number, the less similar the pattern of expression for each gene between condition. 
```

```{r}
#Step 5: Plot the information.

#There are many ways to plot the info in this table. I chose to plot the Euclidean expression distance against the 4000 rad condition HHI score for each gene, represented as a point. I add 95th percentile lines for each axis and map the color of each gene to the log2FC value (irradiated vs unirradiated)

#I chose to include lines on my plot showing the 95th percentile each score. 
COI_distance<-quantile(condition_distance_df$condition_distance,0.95)
COI_HHI<-quantile(condition_distance_df$HHI_R4K,0.95)

#I chose to label only a few genes of interest in the plot, e.g.:
genes_to_label<-c("gene1","gene2","gene3","...")

#Here is example code used to generate the plot. 
ggplot(condition_distance_df%>%arrange(avg_log2FC), aes(x=HHI_R4K,y=condition_distance))+geom_point(aes(color=avg_log2FC),alpha=0.5,size=4) + scale_color_viridis(option="turbo") +scale_x_continuous(breaks=seq(0,1,0.1))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,size=20, face="bold",color="black"),axis.text.y= element_text(size=20,face="bold",color="black"),axis.title.x = element_text(size=20,color="black",face="bold"),axis.title.y=element_text(size=20,face="bold",color="black"), legend.text = element_text(size=20,color="black",face="bold"),legend.title = element_text(size=20,color="black",face="bold"), legend.key.size = unit(1.3,"line"),legend.position = c(0.85, 0.83),legend.background = element_rect(fill="transparent",size=2, linetype="solid", colour ="transparent")) +ylab("0R vs 4000R Euclidean Distance")+xlab("HHI: 4000 Rads (PD Regions)") +geom_hline(aes(yintercept = COI_distance),linetype="dashed",size=1,color="grey40")+geom_vline(aes(xintercept = COI_HHI),linetype="dashed",size=1,color="grey40") +geom_text_repel(aes(label=ifelse(HHI_R4K>0.6|condition_distance>0.4,gene_name,ifelse(gene_name%in%genes_to_label,gene_name,""))), force=0.55,max.overlaps=100000,size=5.5,fontface="bold",color="black",position="dodge",min.segment.length=0.01,segment.size=0.5)+ labs(colour = "Average Log2FC")

ggsave('path_to_save_file',dpi=600, width = 7*1.5,height = 7)
```

